project = "leechpose"
path = "F:/videos"

nesting = 1

video_extension = 'mp4'

[calibration]
# checkerboard / charuco / aruco
board_type = "charuco"

# width and height of grid, in squares
board_size = [9, 4]

# number of bits in the markers, if aruco/charuco
board_marker_bits = 5

# number of markers in dictionary, if aruco/charuco
board_marker_dict_number = 1000

# length of marker side
board_marker_length = 7 # mm

# If aruco, length of marker separation
# board_marker_separation_length = 1 # mm

# If charuco or checkerboard, square side length
board_square_side_length = 9 # mm

animal_calibration = False

calibration_init = 'calibration_init.toml'

[filter]
enabled = true
medfilt = 13
offset_threshold = 25
score_threshold = 0.8
spline = true

[labeling]
scheme = [
    ['L1A', 'L1B', 'L1C', 'L1D', 'L1E'],
    ['L2A', 'L2B', 'L2C', 'L2D', 'L2E'],
    ['L3A', 'L3B', 'L3C', 'L3D', 'L3E']
]

[triangulation]
cam_regex = 'cam([0-9])'
axes = [
    ["x", "L1A", "L3A"],
    ["z", "L1B", "L1A"]
]
reference_point = "L1A"
cam_align = "0"

[angles]
L1_CF = ["L1A", "L1B", "L1C"]
L1_FTi = ["L1B", "L1C", "L1D"]
L1_TiTa = ["L1C", "L1D", "L1E"]

L2_CF = ["L2A", "L2B", "L2C"]
L2_FTi = ["L2B", "L2C", "L2D"]
L2_TiTa = ["L2C", "L2D", "L2E"]

L3_CF = ["L3A", "L3B", "L3C"]
L3_FTi = ["L3B", "L3C", "L3D"]
L3_TiTa = ["L3C", "L3D", "L3E"]


[cameras.A]
offset = [224, 120, 832, 704]

[cameras.B]
offset = [224, 230, 800, 700]

[cameras.C]
offset = [160, 250, 864, 700]